version: '3.9'

services:
  web:
    build: .
    container_name: samjungenc
    command: >
      sh -c "sleep 5 && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=samjungenc.settings
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:17-alpine
    container_name: samjung_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default