# Generated by Django 5.1.6 on 2025-03-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('service_manager', 'Service Manager'), ('teamlead', 'Teamlead'), ('worker', 'Worker')], default='worker', max_length=20),
        ),
    ]
